language: node_js
sudo: false
services:
  - docker
node_js:
  - lts/carbon
cache:
  directories:
    - node_modules
install:
  - yarn
before_script:
  - docker-compose -f docker-compose.test.yml up -d
script:
  - jest --ci --coverage
after_script:
  - docker-compose -f docker-compose.test.yml down
after_success:
  - npx codecov
